# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=100)),
                ('marka', models.CharField(choices=[('samsung', 'SAMSUNG'), ('huawei', 'HUAWEI'), ('sony', 'SONY'), ('motorola', 'MOTOROLA'), ('asus', 'ASUS')], max_length=10)),
                ('kategorija', models.CharField(choices=[('maska', 'MASKA'), ('folija', 'FOLIJA'), ('staklo 2d', 'STAKLO 2D')], max_length=10)),
                ('cena', models.FloatField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Artikli',
            },
        ),
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorija', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Kategorije',
            },
        ),
    ]
