# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 12:24
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(default='Ovaj artikal nema opis!', max_length=100)),
                ('slika', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('cena', models.FloatField()),
                ('na_stanju', models.BooleanField(default=True)),
                ('na_akciji', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-kategorija'],
                'verbose_name_plural': 'Artikli',
            },
        ),
        migrations.CreateModel(
            name='Detalji_korisnika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresa', models.CharField(max_length=50)),
                ('postanski_broj', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(code='Po\u0161tanski broj mora imati 5 cifara', message='Po\u0161tanski broj mora imati 5 cifara', regex='^.{5}$')])),
                ('grad', models.CharField(max_length=25)),
                ('kontakt_telefon', models.CharField(max_length=15)),
                ('korisnik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Detalji korisnika',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ukupno', models.FloatField(default=0.0)),
                ('artikal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eprodaja.Artikal')),
            ],
            options={
                'verbose_name_plural': 'Unosi u korpe',
            },
        ),
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorija', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Kategorije',
            },
        ),
        migrations.CreateModel(
            name='Korpa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(auto_now_add=True)),
                ('ukupno', models.FloatField(default=0.0)),
                ('ukupno_proizvoda_u_korpi', models.PositiveIntegerField(default=0)),
                ('potvrdjena', models.BooleanField(default=False)),
                ('otpremljena', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korpe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datum'],
                'verbose_name_plural': 'Korpe kupaca',
            },
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Marke',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eprodaja.Marka')),
            ],
            options={
                'verbose_name_plural': 'Modeli',
            },
        ),
        migrations.CreateModel(
            name='Poruke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(blank=True, max_length=250, null=True)),
                ('poruka', models.TextField(blank=True, null=True)),
                ('datum', models.DateField(auto_now_add=True)),
                ('procitana', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poruke', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datum'],
                'verbose_name_plural': 'Poruke',
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='korpa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eprodaja.Korpa'),
        ),
        migrations.AddField(
            model_name='artikal',
            name='kategorija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eprodaja.Kategorija'),
        ),
        migrations.AddField(
            model_name='artikal',
            name='marka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eprodaja.Marka'),
        ),
        migrations.AddField(
            model_name='artikal',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eprodaja.Model'),
        ),
    ]
