# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-26 12:15
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('marka', models.CharField(choices=[('samsung', 'SAMSUNG'), ('huawei', 'HUAWEI'), ('sony', 'SONY'), ('motorola', 'MOTOROLA'), ('asus', 'ASUS')], max_length=10)),
                ('kategorija', models.CharField(choices=[('maska', 'MASKA'), ('folija', 'FOLIJA'), ('staklo 2d', 'STAKLO 2D')], max_length=10)),
                ('slika', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('na_stanju', models.BooleanField(default=True)),
                ('na_akciji', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Artikli',
            },
        ),
        migrations.CreateModel(
            name='Detalji_korisnika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresa', models.CharField(max_length=50)),
                ('postanski_broj', models.IntegerField(validators=[django.core.validators.RegexValidator(code='Po\u0161tanski broj mora imati 5 cifara', message='Po\u0161tanski broj mora imati 5 cifara', regex='^.{5}$')])),
                ('grad', models.CharField(max_length=25)),
                ('kontakt_telefon', models.CharField(max_length=15)),
                ('korisnik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Detalji korisnika',
            },
        ),
        migrations.CreateModel(
            name='Korpa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(auto_now_add=True)),
                ('ukupno', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('potvrdjena', models.BooleanField(default=False)),
                ('otpremljena', models.BooleanField(default=False)),
                ('artikli', models.ManyToManyField(blank=True, related_name='korpe', to='eprodaja.Artikal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korpe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Korpe kupaca',
            },
        ),
        migrations.CreateModel(
            name='Poruke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(blank=True, max_length=250, null=True)),
                ('poruka', models.TextField(blank=True, null=True)),
                ('datum', models.DateField(auto_now_add=True)),
                ('procitana', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poruke', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Poruke',
            },
        ),
    ]
