# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 07:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprodaja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalji_korisnika',
            name='adresa',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='detalji_korisnika',
            name='grad',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='detalji_korisnika',
            name='kontakt_telefon',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='detalji_korisnika',
            name='postanski_broj',
            field=models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(code='Po\u0161tanski broj mora imati 5 cifara', message='Po\u0161tanski broj mora imati 5 cifara', regex='^.{5}$')]),
        ),
    ]
